method=ctm_compact
matchBlocks=geostrata:rich_emerald_ore:host=gneiss
connect=block
tiles=geostrata:optifine/ctm/ore/emerald/gneiss/rich/0 geostrata:optifine/ctm/ore/emerald/gneiss/rich/1 geostrata:optifine/ctm/ore/emerald/gneiss/rich/2 geostrata:optifine/ctm/ore/emerald/gneiss/rich/3 geostrata:optifine/ctm/ore/emerald/gneiss/rich/4
innerSeams=false
