method=ctm_compact
matchBlocks=geostrata:rich_emerald_ore:host=limestone
connect=block
tiles=geostrata:optifine/ctm/ore/emerald/limestone/rich/0 geostrata:optifine/ctm/ore/emerald/limestone/rich/1 geostrata:optifine/ctm/ore/emerald/limestone/rich/2 geostrata:optifine/ctm/ore/emerald/limestone/rich/3 geostrata:optifine/ctm/ore/emerald/limestone/rich/4
innerSeams=false
