method=ctm_compact
matchBlocks=geostrata:rich_emerald_ore:host=marble
connect=state
tiles=geostrata:textures/optifine/ctm/ore/emerald/marble/rich/0 geostrata:textures/optifine/ctm/ore/emerald/marble/rich/1 geostrata:textures/optifine/ctm/ore/emerald/marble/rich/2 geostrata:textures/optifine/ctm/ore/emerald/marble/rich/3 geostrata:textures/optifine/ctm/ore/emerald/marble/rich/4
innerSeams=false
