method=ctm_compact
matchBlocks=geostrata:rich_emerald_ore:host=marble
connect=block
tiles=geostrata:optifine/ctm/ore/emerald/marble/rich/0 geostrata:optifine/ctm/ore/emerald/marble/rich/1 geostrata:optifine/ctm/ore/emerald/marble/rich/2 geostrata:optifine/ctm/ore/emerald/marble/rich/3 geostrata:optifine/ctm/ore/emerald/marble/rich/4
innerSeams=false
