method=ctm_compact
matchBlocks=geostrata:rich_emerald_ore:host=slate
connect=block
tiles=geostrata:optifine/ctm/ore/emerald/slate/rich/0 geostrata:optifine/ctm/ore/emerald/slate/rich/1 geostrata:optifine/ctm/ore/emerald/slate/rich/2 geostrata:optifine/ctm/ore/emerald/slate/rich/3 geostrata:optifine/ctm/ore/emerald/slate/rich/4
innerSeams=false
