method=ctm_compact
matchBlocks=geostrata:rich_emerald_ore:host=slate
connect=state
tiles=geostrata:textures/optifine/ctm/ore/emerald/slate/rich/0 geostrata:textures/optifine/ctm/ore/emerald/slate/rich/1 geostrata:textures/optifine/ctm/ore/emerald/slate/rich/2 geostrata:textures/optifine/ctm/ore/emerald/slate/rich/3 geostrata:textures/optifine/ctm/ore/emerald/slate/rich/4
innerSeams=false
