method=ctm_compact
matchBlocks=geostrata:rich_coal_ore:host=mudstone
connect=block
tiles=geostrata:optifine/ctm/ore/coal/mudstone/rich/0 geostrata:optifine/ctm/ore/coal/mudstone/rich/1 geostrata:optifine/ctm/ore/coal/mudstone/rich/2 geostrata:optifine/ctm/ore/coal/mudstone/rich/3 geostrata:optifine/ctm/ore/coal/mudstone/rich/4
innerSeams=false
