method=ctm_compact
matchBlocks=geostrata:rich_coal_ore:host=siltstone
connect=block
tiles=geostrata:optifine/ctm/ore/coal/siltstone/rich/0 geostrata:optifine/ctm/ore/coal/siltstone/rich/1 geostrata:optifine/ctm/ore/coal/siltstone/rich/2 geostrata:optifine/ctm/ore/coal/siltstone/rich/3 geostrata:optifine/ctm/ore/coal/siltstone/rich/4
innerSeams=false
