method=ctm_compact
matchBlocks=geostrata:massive_emerald_ore:host=gneiss
connect=state
tiles=geostrata:textures/optifine/ctm/ore/emerald/gneiss/massive/0 geostrata:textures/optifine/ctm/ore/emerald/gneiss/massive/1 geostrata:textures/optifine/ctm/ore/emerald/gneiss/massive/2 geostrata:textures/optifine/ctm/ore/emerald/gneiss/massive/3 geostrata:textures/optifine/ctm/ore/emerald/gneiss/massive/4
innerSeams=false
