method=ctm_compact
matchBlocks=geostrata:massive_emerald_ore:host=marble
connect=block
tiles=geostrata:textures/optifine/ctm/ore/emerald/marble/massive/0 geostrata:textures/optifine/ctm/ore/emerald/marble/massive/1 geostrata:textures/optifine/ctm/ore/emerald/marble/massive/2 geostrata:textures/optifine/ctm/ore/emerald/marble/massive/3 geostrata:textures/optifine/ctm/ore/emerald/marble/massive/4
innerSeams=false
