method=ctm_compact
matchBlocks=geostrata:massive_emerald_ore:host=shale
connect=state
tiles=geostrata:textures/optifine/ctm/ore/emerald/shale/massive/0 geostrata:textures/optifine/ctm/ore/emerald/shale/massive/1 geostrata:textures/optifine/ctm/ore/emerald/shale/massive/2 geostrata:textures/optifine/ctm/ore/emerald/shale/massive/3 geostrata:textures/optifine/ctm/ore/emerald/shale/massive/4
innerSeams=false
