method=ctm_compact
matchBlocks=geostrata:medium_coal_ore:host=mudstone
connect=state
tiles=geostrata:textures/optifine/ctm/ore/coal/mudstone/medium/0 geostrata:textures/optifine/ctm/ore/coal/mudstone/medium/1 geostrata:textures/optifine/ctm/ore/coal/mudstone/medium/2 geostrata:textures/optifine/ctm/ore/coal/mudstone/medium/3 geostrata:textures/optifine/ctm/ore/coal/mudstone/medium/4
innerSeams=false
