method=ctm_compact
matchBlocks=geostrata:medium_coal_ore:host=siltstone
connect=block
tiles=geostrata:optifine/ctm/ore/coal/siltstone/medium/0 geostrata:optifine/ctm/ore/coal/siltstone/medium/1 geostrata:optifine/ctm/ore/coal/siltstone/medium/2 geostrata:optifine/ctm/ore/coal/siltstone/medium/3 geostrata:optifine/ctm/ore/coal/siltstone/medium/4
innerSeams=false
