method=ctm_compact
matchBlocks=geostrata:medium_coal_ore:host=siltstone
connect=state
tiles=geostrata:textures/optifine/ctm/ore/coal/siltstone/medium/0 geostrata:textures/optifine/ctm/ore/coal/siltstone/medium/1 geostrata:textures/optifine/ctm/ore/coal/siltstone/medium/2 geostrata:textures/optifine/ctm/ore/coal/siltstone/medium/3 geostrata:textures/optifine/ctm/ore/coal/siltstone/medium/4
innerSeams=false
