plugins {
    id 'java'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    options.release = 17
}

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') {
        expand(version: project.version)
    }
}
