method=ctm_compact
matchBlocks=geostrata:poor_copper_ore:host=limestone
connect=block
tiles=geostrata:optifine/ctm/ore/copper/limestone/poor/0 geostrata:optifine/ctm/ore/copper/limestone/poor/1 geostrata:optifine/ctm/ore/copper/limestone/poor/2 geostrata:optifine/ctm/ore/copper/limestone/poor/3 geostrata:optifine/ctm/ore/copper/limestone/poor/4
innerSeams=false
