method=ctm_compact
matchBlocks=geostrata:poor_copper_ore:host=rhyolite
connect=block
tiles=geostrata:optifine/ctm/ore/copper/rhyolite/poor/0 geostrata:optifine/ctm/ore/copper/rhyolite/poor/1 geostrata:optifine/ctm/ore/copper/rhyolite/poor/2 geostrata:optifine/ctm/ore/copper/rhyolite/poor/3 geostrata:optifine/ctm/ore/copper/rhyolite/poor/4
innerSeams=false
