method=ctm_compact
matchBlocks=geostrata:poor_copper_ore:host=rhyolite
connect=state
tiles=geostrata:textures/optifine/ctm/ore/copper/rhyolite/poor/0 geostrata:textures/optifine/ctm/ore/copper/rhyolite/poor/1 geostrata:textures/optifine/ctm/ore/copper/rhyolite/poor/2 geostrata:textures/optifine/ctm/ore/copper/rhyolite/poor/3 geostrata:textures/optifine/ctm/ore/copper/rhyolite/poor/4
innerSeams=false
