method=ctm_compact
matchBlocks=geostrata:medium_iron_ore:host=basalt
connect=block
tiles=geostrata:optifine/ctm/ore/iron/basalt/medium/0 geostrata:optifine/ctm/ore/iron/basalt/medium/1 geostrata:optifine/ctm/ore/iron/basalt/medium/2 geostrata:optifine/ctm/ore/iron/basalt/medium/3 geostrata:optifine/ctm/ore/iron/basalt/medium/4
innerSeams=false
