method=ctm_compact
matchBlocks=geostrata:medium_iron_ore:host=quartzite
connect=state
tiles=geostrata:textures/optifine/ctm/ore/iron/quartzite/medium/0 geostrata:textures/optifine/ctm/ore/iron/quartzite/medium/1 geostrata:textures/optifine/ctm/ore/iron/quartzite/medium/2 geostrata:textures/optifine/ctm/ore/iron/quartzite/medium/3 geostrata:textures/optifine/ctm/ore/iron/quartzite/medium/4
innerSeams=false
