method=ctm_compact
matchBlocks=geostrata:medium_iron_ore:host=quartzite
connect=block
tiles=geostrata:optifine/ctm/ore/iron/quartzite/medium/0 geostrata:optifine/ctm/ore/iron/quartzite/medium/1 geostrata:optifine/ctm/ore/iron/quartzite/medium/2 geostrata:optifine/ctm/ore/iron/quartzite/medium/3 geostrata:optifine/ctm/ore/iron/quartzite/medium/4
innerSeams=false
