method=ctm_compact
matchBlocks=geostrata:medium_iron_ore:host=rhyolite
connect=state
tiles=geostrata:textures/optifine/ctm/ore/iron/rhyolite/medium/0 geostrata:textures/optifine/ctm/ore/iron/rhyolite/medium/1 geostrata:textures/optifine/ctm/ore/iron/rhyolite/medium/2 geostrata:textures/optifine/ctm/ore/iron/rhyolite/medium/3 geostrata:textures/optifine/ctm/ore/iron/rhyolite/medium/4
innerSeams=false
