method=ctm_compact
matchBlocks=geostrata:poor_coal_ore:host=mudstone
connect=block
tiles=geostrata:optifine/ctm/ore/coal/mudstone/poor/0 geostrata:optifine/ctm/ore/coal/mudstone/poor/1 geostrata:optifine/ctm/ore/coal/mudstone/poor/2 geostrata:optifine/ctm/ore/coal/mudstone/poor/3 geostrata:optifine/ctm/ore/coal/mudstone/poor/4
innerSeams=false
