method=ctm_compact
matchBlocks=geostrata:poor_coal_ore:host=mudstone
connect=state
tiles=geostrata:textures/optifine/ctm/ore/coal/mudstone/poor/0 geostrata:textures/optifine/ctm/ore/coal/mudstone/poor/1 geostrata:textures/optifine/ctm/ore/coal/mudstone/poor/2 geostrata:textures/optifine/ctm/ore/coal/mudstone/poor/3 geostrata:textures/optifine/ctm/ore/coal/mudstone/poor/4
innerSeams=false
