method=ctm_compact
matchBlocks=geostrata:poor_coal_ore:host=shale
connect=block
tiles=geostrata:optifine/ctm/ore/coal/shale/poor/0 geostrata:optifine/ctm/ore/coal/shale/poor/1 geostrata:optifine/ctm/ore/coal/shale/poor/2 geostrata:optifine/ctm/ore/coal/shale/poor/3 geostrata:optifine/ctm/ore/coal/shale/poor/4
innerSeams=false
