method=ctm_compact
matchBlocks=geostrata:poor_coal_ore:host=siltstone
connect=block
tiles=geostrata:textures/optifine/ctm/ore/coal/siltstone/poor/0 geostrata:textures/optifine/ctm/ore/coal/siltstone/poor/1 geostrata:textures/optifine/ctm/ore/coal/siltstone/poor/2 geostrata:textures/optifine/ctm/ore/coal/siltstone/poor/3 geostrata:textures/optifine/ctm/ore/coal/siltstone/poor/4
innerSeams=false
