method=ctm_compact
matchBlocks=geostrata:massive_copper_ore:host=basalt
connect=block
tiles=geostrata:optifine/ctm/ore/copper/basalt/massive/0 geostrata:optifine/ctm/ore/copper/basalt/massive/1 geostrata:optifine/ctm/ore/copper/basalt/massive/2 geostrata:optifine/ctm/ore/copper/basalt/massive/3 geostrata:optifine/ctm/ore/copper/basalt/massive/4
innerSeams=false
