method=ctm_compact
matchBlocks=geostrata:massive_copper_ore:host=rhyolite
connect=block
tiles=geostrata:optifine/ctm/ore/copper/rhyolite/massive/0 geostrata:optifine/ctm/ore/copper/rhyolite/massive/1 geostrata:optifine/ctm/ore/copper/rhyolite/massive/2 geostrata:optifine/ctm/ore/copper/rhyolite/massive/3 geostrata:optifine/ctm/ore/copper/rhyolite/massive/4
innerSeams=false
