method=ctm_compact
matchBlocks=geostrata:medium_emerald_ore:host=gneiss
connect=block
tiles=geostrata:optifine/ctm/ore/emerald/gneiss/medium/0 geostrata:optifine/ctm/ore/emerald/gneiss/medium/1 geostrata:optifine/ctm/ore/emerald/gneiss/medium/2 geostrata:optifine/ctm/ore/emerald/gneiss/medium/3 geostrata:optifine/ctm/ore/emerald/gneiss/medium/4
innerSeams=false
