method=ctm_compact
matchBlocks=geostrata:medium_emerald_ore:host=schist
connect=block
tiles=geostrata:textures/optifine/ctm/ore/emerald/schist/medium/0 geostrata:textures/optifine/ctm/ore/emerald/schist/medium/1 geostrata:textures/optifine/ctm/ore/emerald/schist/medium/2 geostrata:textures/optifine/ctm/ore/emerald/schist/medium/3 geostrata:textures/optifine/ctm/ore/emerald/schist/medium/4
innerSeams=false
