method=ctm_compact
matchBlocks=geostrata:medium_emerald_ore:host=shale
connect=block
tiles=geostrata:optifine/ctm/ore/emerald/shale/medium/0 geostrata:optifine/ctm/ore/emerald/shale/medium/1 geostrata:optifine/ctm/ore/emerald/shale/medium/2 geostrata:optifine/ctm/ore/emerald/shale/medium/3 geostrata:optifine/ctm/ore/emerald/shale/medium/4
innerSeams=false
