method=ctm_compact
matchBlocks=geostrata:poor_emerald_ore:host=limestone
connect=block
tiles=geostrata:textures/optifine/ctm/ore/emerald/limestone/poor/0 geostrata:textures/optifine/ctm/ore/emerald/limestone/poor/1 geostrata:textures/optifine/ctm/ore/emerald/limestone/poor/2 geostrata:textures/optifine/ctm/ore/emerald/limestone/poor/3 geostrata:textures/optifine/ctm/ore/emerald/limestone/poor/4
innerSeams=false
