method=ctm_compact
matchBlocks=geostrata:poor_emerald_ore:host=marble
connect=state
tiles=geostrata:textures/optifine/ctm/ore/emerald/marble/poor/0 geostrata:textures/optifine/ctm/ore/emerald/marble/poor/1 geostrata:textures/optifine/ctm/ore/emerald/marble/poor/2 geostrata:textures/optifine/ctm/ore/emerald/marble/poor/3 geostrata:textures/optifine/ctm/ore/emerald/marble/poor/4
innerSeams=false
