method=ctm_compact
matchBlocks=geostrata:poor_emerald_ore:host=shale
connect=block
tiles=geostrata:optifine/ctm/ore/emerald/shale/poor/0 geostrata:optifine/ctm/ore/emerald/shale/poor/1 geostrata:optifine/ctm/ore/emerald/shale/poor/2 geostrata:optifine/ctm/ore/emerald/shale/poor/3 geostrata:optifine/ctm/ore/emerald/shale/poor/4
innerSeams=false
