method=ctm_compact
matchBlocks=geostrata:poor_emerald_ore:host=slate
connect=block
tiles=geostrata:textures/optifine/ctm/ore/emerald/slate/poor/0 geostrata:textures/optifine/ctm/ore/emerald/slate/poor/1 geostrata:textures/optifine/ctm/ore/emerald/slate/poor/2 geostrata:textures/optifine/ctm/ore/emerald/slate/poor/3 geostrata:textures/optifine/ctm/ore/emerald/slate/poor/4
innerSeams=false
