method=ctm_compact
matchBlocks=geostrata:poor_gold_ore:host=basalt
connect=state
tiles=geostrata:textures/optifine/ctm/ore/gold/basalt/poor/0 geostrata:textures/optifine/ctm/ore/gold/basalt/poor/1 geostrata:textures/optifine/ctm/ore/gold/basalt/poor/2 geostrata:textures/optifine/ctm/ore/gold/basalt/poor/3 geostrata:textures/optifine/ctm/ore/gold/basalt/poor/4
innerSeams=false
