method=ctm_compact
matchBlocks=geostrata:poor_gold_ore:host=gneiss
connect=block
tiles=geostrata:optifine/ctm/ore/gold/gneiss/poor/0 geostrata:optifine/ctm/ore/gold/gneiss/poor/1 geostrata:optifine/ctm/ore/gold/gneiss/poor/2 geostrata:optifine/ctm/ore/gold/gneiss/poor/3 geostrata:optifine/ctm/ore/gold/gneiss/poor/4
innerSeams=false
