method=ctm_compact
matchBlocks=geostrata:poor_gold_ore:host=marble
connect=block
tiles=geostrata:optifine/ctm/ore/gold/marble/poor/0 geostrata:optifine/ctm/ore/gold/marble/poor/1 geostrata:optifine/ctm/ore/gold/marble/poor/2 geostrata:optifine/ctm/ore/gold/marble/poor/3 geostrata:optifine/ctm/ore/gold/marble/poor/4
innerSeams=false
