method=ctm_compact
matchBlocks=geostrata:poor_gold_ore:host=quartzite
connect=block
tiles=geostrata:optifine/ctm/ore/gold/quartzite/poor/0 geostrata:optifine/ctm/ore/gold/quartzite/poor/1 geostrata:optifine/ctm/ore/gold/quartzite/poor/2 geostrata:optifine/ctm/ore/gold/quartzite/poor/3 geostrata:optifine/ctm/ore/gold/quartzite/poor/4
innerSeams=false
