method=ctm_compact
matchBlocks=geostrata:poor_gold_ore:host=rhyolite
connect=block
tiles=geostrata:optifine/ctm/ore/gold/rhyolite/poor/0 geostrata:optifine/ctm/ore/gold/rhyolite/poor/1 geostrata:optifine/ctm/ore/gold/rhyolite/poor/2 geostrata:optifine/ctm/ore/gold/rhyolite/poor/3 geostrata:optifine/ctm/ore/gold/rhyolite/poor/4
innerSeams=false
