method=ctm_compact
matchBlocks=geostrata:poor_gold_ore:host=schist
connect=block
tiles=geostrata:textures/optifine/ctm/ore/gold/schist/poor/0 geostrata:textures/optifine/ctm/ore/gold/schist/poor/1 geostrata:textures/optifine/ctm/ore/gold/schist/poor/2 geostrata:textures/optifine/ctm/ore/gold/schist/poor/3 geostrata:textures/optifine/ctm/ore/gold/schist/poor/4
innerSeams=false
