method=ctm_compact
matchBlocks=geostrata:poor_gold_ore:host=slate
connect=state
tiles=geostrata:textures/optifine/ctm/ore/gold/slate/poor/0 geostrata:textures/optifine/ctm/ore/gold/slate/poor/1 geostrata:textures/optifine/ctm/ore/gold/slate/poor/2 geostrata:textures/optifine/ctm/ore/gold/slate/poor/3 geostrata:textures/optifine/ctm/ore/gold/slate/poor/4
innerSeams=false
