method=ctm_compact
matchBlocks=geostrata:medium_copper_ore:host=limestone
connect=block
tiles=geostrata:optifine/ctm/ore/copper/limestone/medium/0 geostrata:optifine/ctm/ore/copper/limestone/medium/1 geostrata:optifine/ctm/ore/copper/limestone/medium/2 geostrata:optifine/ctm/ore/copper/limestone/medium/3 geostrata:optifine/ctm/ore/copper/limestone/medium/4
innerSeams=false
