method=random
matchTiles=geostrata:block/host/basalt
tiles=geostrata:optifine/ctm/host/basalt/0 geostrata:optifine/ctm/host/basalt/1 geostrata:optifine/ctm/host/basalt/2 geostrata:optifine/ctm/host/basalt/3
