method=random
matchTiles=geostrata:block/host/basalt
prioritize=false
tiles=geostrata:textures/optifine/ctm/host/basalt/0 geostrata:textures/optifine/ctm/host/basalt/1 geostrata:textures/optifine/ctm/host/basalt/2 geostrata:textures/optifine/ctm/host/basalt/3
