method=random
matchTiles=geostrata:block/host/breccia
prioritize=false
tiles=geostrata:textures/optifine/ctm/host/breccia/0 geostrata:textures/optifine/ctm/host/breccia/1 geostrata:textures/optifine/ctm/host/breccia/2 geostrata:textures/optifine/ctm/host/breccia/3
