method=random
matchTiles=geostrata:block/host/breccia
tiles=geostrata:optifine/ctm/host/breccia/0 geostrata:optifine/ctm/host/breccia/1 geostrata:optifine/ctm/host/breccia/2 geostrata:optifine/ctm/host/breccia/3
