method=random
matchTiles=geostrata:block/host/chalk
prioritize=false
tiles=geostrata:textures/optifine/ctm/host/chalk/0 geostrata:textures/optifine/ctm/host/chalk/1 geostrata:textures/optifine/ctm/host/chalk/2 geostrata:textures/optifine/ctm/host/chalk/3
