method=random
matchTiles=geostrata:block/host/chalk
tiles=geostrata:optifine/ctm/host/chalk/0 geostrata:optifine/ctm/host/chalk/1 geostrata:optifine/ctm/host/chalk/2 geostrata:optifine/ctm/host/chalk/3
