method=random
matchTiles=geostrata:block/host/conglomerate
prioritize=false
tiles=geostrata:textures/optifine/ctm/host/conglomerate/0 geostrata:textures/optifine/ctm/host/conglomerate/1 geostrata:textures/optifine/ctm/host/conglomerate/2 geostrata:textures/optifine/ctm/host/conglomerate/3
