method=random
matchTiles=geostrata:block/host/conglomerate
tiles=geostrata:optifine/ctm/host/conglomerate/0 geostrata:optifine/ctm/host/conglomerate/1 geostrata:optifine/ctm/host/conglomerate/2 geostrata:optifine/ctm/host/conglomerate/3
