method=random
matchTiles=geostrata:block/host/gabbro
prioritize=false
tiles=geostrata:textures/optifine/ctm/host/gabbro/0 geostrata:textures/optifine/ctm/host/gabbro/1 geostrata:textures/optifine/ctm/host/gabbro/2 geostrata:textures/optifine/ctm/host/gabbro/3
