method=random
matchTiles=geostrata:block/host/gneiss
prioritize=false
tiles=geostrata:textures/optifine/ctm/host/gneiss/0 geostrata:textures/optifine/ctm/host/gneiss/1 geostrata:textures/optifine/ctm/host/gneiss/2 geostrata:textures/optifine/ctm/host/gneiss/3
