method=random
matchTiles=geostrata:block/host/gneiss
tiles=geostrata:optifine/ctm/host/gneiss/0 geostrata:optifine/ctm/host/gneiss/1 geostrata:optifine/ctm/host/gneiss/2 geostrata:optifine/ctm/host/gneiss/3
