method=random
matchTiles=geostrata:block/host/granite
prioritize=false
tiles=geostrata:textures/optifine/ctm/host/granite/0 geostrata:textures/optifine/ctm/host/granite/1 geostrata:textures/optifine/ctm/host/granite/2 geostrata:textures/optifine/ctm/host/granite/3
