method=random
matchTiles=geostrata:block/host/limestone
tiles=geostrata:optifine/ctm/host/limestone/0 geostrata:optifine/ctm/host/limestone/1 geostrata:optifine/ctm/host/limestone/2 geostrata:optifine/ctm/host/limestone/3
