method=random
matchTiles=geostrata:block/host/limestone
prioritize=false
tiles=geostrata:textures/optifine/ctm/host/limestone/0 geostrata:textures/optifine/ctm/host/limestone/1 geostrata:textures/optifine/ctm/host/limestone/2 geostrata:textures/optifine/ctm/host/limestone/3
