method=random
matchTiles=geostrata:block/host/marble
tiles=geostrata:optifine/ctm/host/marble/0 geostrata:optifine/ctm/host/marble/1 geostrata:optifine/ctm/host/marble/2 geostrata:optifine/ctm/host/marble/3
