method=random
matchTiles=geostrata:block/host/mudstone
tiles=geostrata:optifine/ctm/host/mudstone/0 geostrata:optifine/ctm/host/mudstone/1 geostrata:optifine/ctm/host/mudstone/2 geostrata:optifine/ctm/host/mudstone/3
