method=random
matchTiles=geostrata:block/host/peridotite
prioritize=false
tiles=geostrata:textures/optifine/ctm/host/peridotite/0 geostrata:textures/optifine/ctm/host/peridotite/1 geostrata:textures/optifine/ctm/host/peridotite/2 geostrata:textures/optifine/ctm/host/peridotite/3
