method=random
matchTiles=geostrata:block/host/quartzite
tiles=geostrata:optifine/ctm/host/quartzite/0 geostrata:optifine/ctm/host/quartzite/1 geostrata:optifine/ctm/host/quartzite/2 geostrata:optifine/ctm/host/quartzite/3
