method=random
matchTiles=geostrata:block/host/rhyolite
tiles=geostrata:optifine/ctm/host/rhyolite/0 geostrata:optifine/ctm/host/rhyolite/1 geostrata:optifine/ctm/host/rhyolite/2 geostrata:optifine/ctm/host/rhyolite/3
