method=random
matchTiles=geostrata:block/host/schist
prioritize=false
tiles=geostrata:textures/optifine/ctm/host/schist/0 geostrata:textures/optifine/ctm/host/schist/1 geostrata:textures/optifine/ctm/host/schist/2 geostrata:textures/optifine/ctm/host/schist/3
