method=random
matchTiles=geostrata:block/host/schist
tiles=geostrata:optifine/ctm/host/schist/0 geostrata:optifine/ctm/host/schist/1 geostrata:optifine/ctm/host/schist/2 geostrata:optifine/ctm/host/schist/3
