method=random
matchTiles=geostrata:block/host/shale
prioritize=false
tiles=geostrata:textures/optifine/ctm/host/shale/0 geostrata:textures/optifine/ctm/host/shale/1 geostrata:textures/optifine/ctm/host/shale/2 geostrata:textures/optifine/ctm/host/shale/3
