method=random
matchTiles=geostrata:block/host/shale
tiles=geostrata:optifine/ctm/host/shale/0 geostrata:optifine/ctm/host/shale/1 geostrata:optifine/ctm/host/shale/2 geostrata:optifine/ctm/host/shale/3
