method=random
matchTiles=geostrata:block/host/siltstone
tiles=geostrata:optifine/ctm/host/siltstone/0 geostrata:optifine/ctm/host/siltstone/1 geostrata:optifine/ctm/host/siltstone/2 geostrata:optifine/ctm/host/siltstone/3
