method=random
matchTiles=geostrata:block/host/siltstone
prioritize=false
tiles=geostrata:textures/optifine/ctm/host/siltstone/0 geostrata:textures/optifine/ctm/host/siltstone/1 geostrata:textures/optifine/ctm/host/siltstone/2 geostrata:textures/optifine/ctm/host/siltstone/3
