method=random
matchTiles=geostrata:block/host/slate
tiles=geostrata:optifine/ctm/host/slate/0 geostrata:optifine/ctm/host/slate/1 geostrata:optifine/ctm/host/slate/2 geostrata:optifine/ctm/host/slate/3
