method=random
matchTiles=geostrata:block/host/slate
prioritize=false
tiles=geostrata:textures/optifine/ctm/host/slate/0 geostrata:textures/optifine/ctm/host/slate/1 geostrata:textures/optifine/ctm/host/slate/2 geostrata:textures/optifine/ctm/host/slate/3
