method=ctm_compact
matchBlocks=geostrata:rich_gold_ore:host=basalt
connect=block
tiles=geostrata:optifine/ctm/ore/gold/basalt/rich/0 geostrata:optifine/ctm/ore/gold/basalt/rich/1 geostrata:optifine/ctm/ore/gold/basalt/rich/2 geostrata:optifine/ctm/ore/gold/basalt/rich/3 geostrata:optifine/ctm/ore/gold/basalt/rich/4
innerSeams=false
