method=ctm_compact
matchBlocks=geostrata:rich_gold_ore:host=basalt
connect=state
tiles=geostrata:textures/optifine/ctm/ore/gold/basalt/rich/0 geostrata:textures/optifine/ctm/ore/gold/basalt/rich/1 geostrata:textures/optifine/ctm/ore/gold/basalt/rich/2 geostrata:textures/optifine/ctm/ore/gold/basalt/rich/3 geostrata:textures/optifine/ctm/ore/gold/basalt/rich/4
innerSeams=false
