method=ctm_compact
matchBlocks=geostrata:rich_gold_ore:host=quartzite
connect=block
tiles=geostrata:optifine/ctm/ore/gold/quartzite/rich/0 geostrata:optifine/ctm/ore/gold/quartzite/rich/1 geostrata:optifine/ctm/ore/gold/quartzite/rich/2 geostrata:optifine/ctm/ore/gold/quartzite/rich/3 geostrata:optifine/ctm/ore/gold/quartzite/rich/4
innerSeams=false
