method=ctm_compact
matchBlocks=geostrata:rich_gold_ore:host=schist
connect=block
tiles=geostrata:optifine/ctm/ore/gold/schist/rich/0 geostrata:optifine/ctm/ore/gold/schist/rich/1 geostrata:optifine/ctm/ore/gold/schist/rich/2 geostrata:optifine/ctm/ore/gold/schist/rich/3 geostrata:optifine/ctm/ore/gold/schist/rich/4
innerSeams=false
