method=ctm_compact
matchBlocks=geostrata:rich_gold_ore:host=slate
connect=block
tiles=geostrata:textures/optifine/ctm/ore/gold/slate/rich/0 geostrata:textures/optifine/ctm/ore/gold/slate/rich/1 geostrata:textures/optifine/ctm/ore/gold/slate/rich/2 geostrata:textures/optifine/ctm/ore/gold/slate/rich/3 geostrata:textures/optifine/ctm/ore/gold/slate/rich/4
innerSeams=false
