method=ctm_compact
matchBlocks=geostrata:massive_iron_ore:host=basalt
connect=block
tiles=geostrata:textures/optifine/ctm/ore/iron/basalt/massive/0 geostrata:textures/optifine/ctm/ore/iron/basalt/massive/1 geostrata:textures/optifine/ctm/ore/iron/basalt/massive/2 geostrata:textures/optifine/ctm/ore/iron/basalt/massive/3 geostrata:textures/optifine/ctm/ore/iron/basalt/massive/4
innerSeams=false
