method=ctm_compact
matchBlocks=geostrata:massive_iron_ore:host=limestone
connect=state
tiles=geostrata:textures/optifine/ctm/ore/iron/limestone/massive/0 geostrata:textures/optifine/ctm/ore/iron/limestone/massive/1 geostrata:textures/optifine/ctm/ore/iron/limestone/massive/2 geostrata:textures/optifine/ctm/ore/iron/limestone/massive/3 geostrata:textures/optifine/ctm/ore/iron/limestone/massive/4
innerSeams=false
