method=ctm_compact
matchBlocks=geostrata:massive_iron_ore:host=quartzite
connect=state
tiles=geostrata:textures/optifine/ctm/ore/iron/quartzite/massive/0 geostrata:textures/optifine/ctm/ore/iron/quartzite/massive/1 geostrata:textures/optifine/ctm/ore/iron/quartzite/massive/2 geostrata:textures/optifine/ctm/ore/iron/quartzite/massive/3 geostrata:textures/optifine/ctm/ore/iron/quartzite/massive/4
innerSeams=false
