method=ctm_compact
matchBlocks=geostrata:massive_iron_ore:host=rhyolite
connect=state
tiles=geostrata:textures/optifine/ctm/ore/iron/rhyolite/massive/0 geostrata:textures/optifine/ctm/ore/iron/rhyolite/massive/1 geostrata:textures/optifine/ctm/ore/iron/rhyolite/massive/2 geostrata:textures/optifine/ctm/ore/iron/rhyolite/massive/3 geostrata:textures/optifine/ctm/ore/iron/rhyolite/massive/4
innerSeams=false
