method=ctm_compact
matchBlocks=geostrata:medium_gold_ore:host=rhyolite
connect=block
tiles=geostrata:optifine/ctm/ore/gold/rhyolite/medium/0 geostrata:optifine/ctm/ore/gold/rhyolite/medium/1 geostrata:optifine/ctm/ore/gold/rhyolite/medium/2 geostrata:optifine/ctm/ore/gold/rhyolite/medium/3 geostrata:optifine/ctm/ore/gold/rhyolite/medium/4
innerSeams=false
