method=ctm_compact
matchBlocks=geostrata:medium_gold_ore:host=schist
connect=block
tiles=geostrata:optifine/ctm/ore/gold/schist/medium/0 geostrata:optifine/ctm/ore/gold/schist/medium/1 geostrata:optifine/ctm/ore/gold/schist/medium/2 geostrata:optifine/ctm/ore/gold/schist/medium/3 geostrata:optifine/ctm/ore/gold/schist/medium/4
innerSeams=false
