method=ctm_compact
matchBlocks=geostrata:medium_gold_ore:host=slate
connect=block
tiles=geostrata:optifine/ctm/ore/gold/slate/medium/0 geostrata:optifine/ctm/ore/gold/slate/medium/1 geostrata:optifine/ctm/ore/gold/slate/medium/2 geostrata:optifine/ctm/ore/gold/slate/medium/3 geostrata:optifine/ctm/ore/gold/slate/medium/4
innerSeams=false
