method=ctm_compact
matchBlocks=geostrata:massive_gold_ore:host=basalt
connect=state
tiles=geostrata:textures/optifine/ctm/ore/gold/basalt/massive/0 geostrata:textures/optifine/ctm/ore/gold/basalt/massive/1 geostrata:textures/optifine/ctm/ore/gold/basalt/massive/2 geostrata:textures/optifine/ctm/ore/gold/basalt/massive/3 geostrata:textures/optifine/ctm/ore/gold/basalt/massive/4
innerSeams=false
