method=ctm_compact
matchBlocks=geostrata:massive_gold_ore:host=gneiss
connect=block
tiles=geostrata:optifine/ctm/ore/gold/gneiss/massive/0 geostrata:optifine/ctm/ore/gold/gneiss/massive/1 geostrata:optifine/ctm/ore/gold/gneiss/massive/2 geostrata:optifine/ctm/ore/gold/gneiss/massive/3 geostrata:optifine/ctm/ore/gold/gneiss/massive/4
innerSeams=false
