method=ctm_compact
matchBlocks=geostrata:massive_gold_ore:host=quartzite
connect=block
tiles=geostrata:optifine/ctm/ore/gold/quartzite/massive/0 geostrata:optifine/ctm/ore/gold/quartzite/massive/1 geostrata:optifine/ctm/ore/gold/quartzite/massive/2 geostrata:optifine/ctm/ore/gold/quartzite/massive/3 geostrata:optifine/ctm/ore/gold/quartzite/massive/4
innerSeams=false
