method=ctm_compact
matchBlocks=geostrata:massive_gold_ore:host=rhyolite
connect=block
tiles=geostrata:textures/optifine/ctm/ore/gold/rhyolite/massive/0 geostrata:textures/optifine/ctm/ore/gold/rhyolite/massive/1 geostrata:textures/optifine/ctm/ore/gold/rhyolite/massive/2 geostrata:textures/optifine/ctm/ore/gold/rhyolite/massive/3 geostrata:textures/optifine/ctm/ore/gold/rhyolite/massive/4
innerSeams=false
