method=ctm_compact
matchBlocks=geostrata:massive_gold_ore:host=schist
connect=block
tiles=geostrata:optifine/ctm/ore/gold/schist/massive/0 geostrata:optifine/ctm/ore/gold/schist/massive/1 geostrata:optifine/ctm/ore/gold/schist/massive/2 geostrata:optifine/ctm/ore/gold/schist/massive/3 geostrata:optifine/ctm/ore/gold/schist/massive/4
innerSeams=false
