method=ctm_compact
matchBlocks=geostrata:massive_gold_ore:host=slate
connect=block
tiles=geostrata:optifine/ctm/ore/gold/slate/massive/0 geostrata:optifine/ctm/ore/gold/slate/massive/1 geostrata:optifine/ctm/ore/gold/slate/massive/2 geostrata:optifine/ctm/ore/gold/slate/massive/3 geostrata:optifine/ctm/ore/gold/slate/massive/4
innerSeams=false
