method=ctm_compact
matchBlocks=geostrata:massive_gold_ore:host=slate
connect=state
tiles=geostrata:textures/optifine/ctm/ore/gold/slate/massive/0 geostrata:textures/optifine/ctm/ore/gold/slate/massive/1 geostrata:textures/optifine/ctm/ore/gold/slate/massive/2 geostrata:textures/optifine/ctm/ore/gold/slate/massive/3 geostrata:textures/optifine/ctm/ore/gold/slate/massive/4
innerSeams=false
