method=ctm_compact
matchBlocks=geostrata:rich_copper_ore:host=limestone
connect=state
tiles=geostrata:textures/optifine/ctm/ore/copper/limestone/rich/0 geostrata:textures/optifine/ctm/ore/copper/limestone/rich/1 geostrata:textures/optifine/ctm/ore/copper/limestone/rich/2 geostrata:textures/optifine/ctm/ore/copper/limestone/rich/3 geostrata:textures/optifine/ctm/ore/copper/limestone/rich/4
innerSeams=false
