method=ctm_compact
matchBlocks=geostrata:rich_copper_ore:host=rhyolite
connect=state
tiles=geostrata:textures/optifine/ctm/ore/copper/rhyolite/rich/0 geostrata:textures/optifine/ctm/ore/copper/rhyolite/rich/1 geostrata:textures/optifine/ctm/ore/copper/rhyolite/rich/2 geostrata:textures/optifine/ctm/ore/copper/rhyolite/rich/3 geostrata:textures/optifine/ctm/ore/copper/rhyolite/rich/4
innerSeams=false
