method=ctm_compact
matchBlocks=geostrata:rich_copper_ore:host=rhyolite
connect=block
tiles=geostrata:optifine/ctm/ore/copper/rhyolite/rich/0 geostrata:optifine/ctm/ore/copper/rhyolite/rich/1 geostrata:optifine/ctm/ore/copper/rhyolite/rich/2 geostrata:optifine/ctm/ore/copper/rhyolite/rich/3 geostrata:optifine/ctm/ore/copper/rhyolite/rich/4
innerSeams=false
