method=ctm_compact
matchBlocks=geostrata:rich_copper_ore:host=shale
connect=block
tiles=geostrata:optifine/ctm/ore/copper/shale/rich/0 geostrata:optifine/ctm/ore/copper/shale/rich/1 geostrata:optifine/ctm/ore/copper/shale/rich/2 geostrata:optifine/ctm/ore/copper/shale/rich/3 geostrata:optifine/ctm/ore/copper/shale/rich/4
innerSeams=false
