method=ctm_compact
matchBlocks=geostrata:poor_iron_ore:host=basalt
connect=state
tiles=geostrata:textures/optifine/ctm/ore/iron/basalt/poor/0 geostrata:textures/optifine/ctm/ore/iron/basalt/poor/1 geostrata:textures/optifine/ctm/ore/iron/basalt/poor/2 geostrata:textures/optifine/ctm/ore/iron/basalt/poor/3 geostrata:textures/optifine/ctm/ore/iron/basalt/poor/4
innerSeams=false
