method=ctm_compact
matchBlocks=geostrata:poor_iron_ore:host=quartzite
connect=state
tiles=geostrata:textures/optifine/ctm/ore/iron/quartzite/poor/0 geostrata:textures/optifine/ctm/ore/iron/quartzite/poor/1 geostrata:textures/optifine/ctm/ore/iron/quartzite/poor/2 geostrata:textures/optifine/ctm/ore/iron/quartzite/poor/3 geostrata:textures/optifine/ctm/ore/iron/quartzite/poor/4
innerSeams=false
