method=ctm_compact
matchBlocks=geostrata:poor_iron_ore:host=rhyolite
connect=block
tiles=geostrata:textures/optifine/ctm/ore/iron/rhyolite/poor/0 geostrata:textures/optifine/ctm/ore/iron/rhyolite/poor/1 geostrata:textures/optifine/ctm/ore/iron/rhyolite/poor/2 geostrata:textures/optifine/ctm/ore/iron/rhyolite/poor/3 geostrata:textures/optifine/ctm/ore/iron/rhyolite/poor/4
innerSeams=false
