method=ctm_compact
matchBlocks=geostrata:poor_iron_ore:host=shale
connect=block
tiles=geostrata:optifine/ctm/ore/iron/shale/poor/0 geostrata:optifine/ctm/ore/iron/shale/poor/1 geostrata:optifine/ctm/ore/iron/shale/poor/2 geostrata:optifine/ctm/ore/iron/shale/poor/3 geostrata:optifine/ctm/ore/iron/shale/poor/4
innerSeams=false
