method=ctm_compact
matchBlocks=geostrata:poor_iron_ore:host=shale
connect=state
tiles=geostrata:textures/optifine/ctm/ore/iron/shale/poor/0 geostrata:textures/optifine/ctm/ore/iron/shale/poor/1 geostrata:textures/optifine/ctm/ore/iron/shale/poor/2 geostrata:textures/optifine/ctm/ore/iron/shale/poor/3 geostrata:textures/optifine/ctm/ore/iron/shale/poor/4
innerSeams=false
