method=ctm_compact
matchBlocks=geostrata:massive_coal_ore:host=mudstone
connect=block
tiles=geostrata:optifine/ctm/ore/coal/mudstone/massive/0 geostrata:optifine/ctm/ore/coal/mudstone/massive/1 geostrata:optifine/ctm/ore/coal/mudstone/massive/2 geostrata:optifine/ctm/ore/coal/mudstone/massive/3 geostrata:optifine/ctm/ore/coal/mudstone/massive/4
innerSeams=false
