method=ctm_compact
matchBlocks=geostrata:massive_coal_ore:host=shale
connect=block
tiles=geostrata:optifine/ctm/ore/coal/shale/massive/0 geostrata:optifine/ctm/ore/coal/shale/massive/1 geostrata:optifine/ctm/ore/coal/shale/massive/2 geostrata:optifine/ctm/ore/coal/shale/massive/3 geostrata:optifine/ctm/ore/coal/shale/massive/4
innerSeams=false
