method=ctm_compact
matchBlocks=geostrata:massive_coal_ore:host=siltstone
connect=block
tiles=geostrata:textures/optifine/ctm/ore/coal/siltstone/massive/0 geostrata:textures/optifine/ctm/ore/coal/siltstone/massive/1 geostrata:textures/optifine/ctm/ore/coal/siltstone/massive/2 geostrata:textures/optifine/ctm/ore/coal/siltstone/massive/3 geostrata:textures/optifine/ctm/ore/coal/siltstone/massive/4
innerSeams=false
