method=ctm_compact
matchBlocks=geostrata:rich_iron_ore:host=basalt
connect=block
tiles=geostrata:optifine/ctm/ore/iron/basalt/rich/0 geostrata:optifine/ctm/ore/iron/basalt/rich/1 geostrata:optifine/ctm/ore/iron/basalt/rich/2 geostrata:optifine/ctm/ore/iron/basalt/rich/3 geostrata:optifine/ctm/ore/iron/basalt/rich/4
innerSeams=false
