method=ctm_compact
matchBlocks=geostrata:rich_iron_ore:host=basalt
connect=state
tiles=geostrata:textures/optifine/ctm/ore/iron/basalt/rich/0 geostrata:textures/optifine/ctm/ore/iron/basalt/rich/1 geostrata:textures/optifine/ctm/ore/iron/basalt/rich/2 geostrata:textures/optifine/ctm/ore/iron/basalt/rich/3 geostrata:textures/optifine/ctm/ore/iron/basalt/rich/4
innerSeams=false
