method=ctm_compact
matchBlocks=geostrata:rich_iron_ore:host=limestone
connect=state
tiles=geostrata:textures/optifine/ctm/ore/iron/limestone/rich/0 geostrata:textures/optifine/ctm/ore/iron/limestone/rich/1 geostrata:textures/optifine/ctm/ore/iron/limestone/rich/2 geostrata:textures/optifine/ctm/ore/iron/limestone/rich/3 geostrata:textures/optifine/ctm/ore/iron/limestone/rich/4
innerSeams=false
