method=ctm_compact
matchBlocks=geostrata:rich_iron_ore:host=rhyolite
connect=block
tiles=geostrata:textures/optifine/ctm/ore/iron/rhyolite/rich/0 geostrata:textures/optifine/ctm/ore/iron/rhyolite/rich/1 geostrata:textures/optifine/ctm/ore/iron/rhyolite/rich/2 geostrata:textures/optifine/ctm/ore/iron/rhyolite/rich/3 geostrata:textures/optifine/ctm/ore/iron/rhyolite/rich/4
innerSeams=false
